import React,{useState}from'react';import{useNavigate}from'react-router-dom';
export default function AgronomyCalc(){const navigate=useNavigate();
const[activeTab,setActiveTab]=useState('Environment');const[guideTab,setGuideTab]=useState('Lighting');
const[tempF,setTempF]=useState('78');const[rh,setRh]=useState('55');const[ppfd,setPpfd]=useState('900');
const[lightHours,setLightHours]=useState('12');const[tentL,setTentL]=useState('4');const[tentW,setTentW]=useState('4');
const[tentH,setTentH]=useState('6.5');const[targetCo2,setTargetCo2]=useState('1200');const[hasFilter,setHasFilter]=useState(true);
const[powerWatts,setPowerWatts]=useState('480');const[kwhRate,setKwhRate]=useState('0.14');
const[feedPpm,setFeedPpm]=useState('600');const[runoffPpm,setRunoffPpm]=useState('850');const[inputEc,setInputEc]=useState('1.6');
const[potSizeGal,setPotSizeGal]=useState('5');const[wetWeight,setWetWeight]=useState('1000');const[rosinInput,setRosinInput]=useState('28');
const[rosinOutput,setRosinOutput]=useState('5.6');const[rawAcidMass,setRawAcidMass]=useState('100');const[inputBiomass,setInputBiomass]=useState('454');
const[targetYield,setTargetYield]=useState('15');const[crudeMass,setCrudeMass]=useState('10');const[crudePurity,setCrudePurity]=useState('75');
const[carrierVol,setCarrierVol]=useState('30');const parse=(val)=>parseFloat(val)||0;
const dli=(parse(ppfd)*parse(lightHours)*3600)/1000000;const tC=(parse(tempF)-32)*(5/9);const svp=0.61078*Math.exp((17.27*tC)/(tC+237.3));const vpd=svp*(1-(parse(rh)/100));
let vpdStatus={text:"Optimal Transpiration",color:"#00cc66"};if(vpd<0.8)vpdStatus={text:"Low VPD (High Mold Risk / Stagnant)",color:"#3b82f6"};if(vpd>1.4)vpdStatus={text:"High VPD (Plant Stress / Stomata Close)",color:"#ef4444"};
const tentCuFt=parse(tentL)*parse(tentW)*parse(tentH);const co2NeededCuFt=tentCuFt*((parse(targetCo2)-400)/1000000);const reqCfm=tentCuFt*(hasFilter?1.35:1.0);
const dailyKwh=(parse(powerWatts)*parse(lightHours))/1000;const monthlyCost=dailyKwh*parse(kwhRate)*30.4;
const ecVal=parse(inputEc);const ppm500=ecVal*500;const ppm700=ecVal*700;const flushGal=parse(potSizeGal)*3;
const ppmDelta=parse(runoffPpm)-parse(feedPpm);let runoffStatus={text:"Optimal Nutrient Consumption",color:"#00cc66"};
if(ppmDelta>300)runoffStatus={text:"Salt Accumulation (Flush)",color:"#ef4444"};if(ppmDelta<-100)runoffStatus={text:"Underfed (Increase PPM)",color:"#f59e0b"};
const estDryYield=parse(wetWeight)*0.22;const rosinYieldPct=parse(rosinInput)>0?(parse(rosinOutput)/parse(rosinInput))*100:0;
const postDecarbActive=parse(rawAcidMass)*0.877;const estCrude=parse(inputBiomass)*(parse(targetYield)/100);
const totalActive=parse(crudeMass)*1000*(parse(crudePurity)/100);const concentration=parse(carrierVol)>0?(totalActive/parse(carrierVol)):0;
const inputStyle={width:'100%',padding:'10px',background:'#000',border:'1px solid #333',borderRadius:'8px',color:'#fff',fontSize:'1.05em',marginTop:'4px'};
const labelStyle={color:'#00ffff',fontSize:'0.8em',fontWeight:'bold',textTransform:'uppercase',letterSpacing:'0.5px'};
const cardStyle={background:'#111',borderRadius:'12px',border:'1px solid #333',padding:'15px',marginBottom:'15px'};
const infoBlockStyle={background:'rgba(255,255,255,0.03)',border:'1px solid #222',borderRadius:'8px',padding:'10px',marginBottom:'12px',fontSize:'0.82em',lineHeight:'1.4'};
return (<div className="view-wrapper" style={{background:'#0a0a0a',minHeight:'100vh',display:'flex',flexDirection:'column'}}>
<header className="header" style={{borderBottom:'1px solid #222'}}><button className="back-btn" onClick={()=>navigate('/')}>← Hub</button><h2>Agronomy & Extract</h2></header>
<div style={{display:'flex',background:'#111',padding:'10px',borderBottom:'1px solid #333',gap:'6px',overflowX:'auto',scrollbarWidth:'none'}}>
{['Environment','Nutrients','Extract','Guide'].map(tab=>(<button key={tab} onClick={()=>setActiveTab(tab)} style={{flex:1,padding:'8px 10px',borderRadius:'8px',fontWeight:'bold',border:'none',whiteSpace:'nowrap',background:activeTab===tab?'#00cc66':'#222',color:activeTab===tab?'#000':'#aaa'}}>{tab}</button>))}</div>
<div className="calc-content" style={{padding:'15px',overflowY:'auto',flex:1,paddingBottom:'95px'}}>
{activeTab==='Environment'&&(<>
<div style={{...cardStyle,borderTop:'4px solid #ef4444'}}><h3 style={{margin:'0 0 6px 0',color:'#ef4444'}}>Vapor Pressure Deficit (VPD)</h3><div style={infoBlockStyle}><div style={{color:'#00ffff',fontWeight:'bold'}}>What it does:</div><div style={{color:'#ccc'}}>Measures atmospheric drying potential between leaf stomata and room air.</div></div><div style={{display:'flex',gap:'10px',marginBottom:'15px'}}><div style={{flex:1}}><label style={{...labelStyle,color:'#ef4444'}}>Temp (°F)<input type="number" value={tempF} onChange={e=>setTempF(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={{...labelStyle,color:'#ef4444'}}>Humidity (%)<input type="number" value={rh} onChange={e=>setRh(e.target.value)} style={inputStyle} /></label></div></div><div style={{background:'#000',padding:'15px',borderRadius:'8px',border:'1px solid #222',textAlign:'center'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'10px'}}><strong style={{color:'#fff',fontSize:'1.1em'}}>VPD:</strong><strong style={{color:vpdStatus.color,fontSize:'1.3em'}}>{vpd.toFixed(2)} kPa</strong></div><div style={{padding:'8px',background:'rgba(255,255,255,0.05)',borderRadius:'6px',color:vpdStatus.color,fontWeight:'bold',fontSize:'0.9em'}}>{vpdStatus.text}</div></div></div>
<div style={{...cardStyle,borderTop:'4px solid #f59e0b'}}><h3 style={{margin:'0 0 6px 0',color:'#f59e0b'}}>Photobiology (DLI)</h3><div style={infoBlockStyle}><div style={{color:'#00ffff',fontWeight:'bold'}}>What it does:</div><div style={{color:'#ccc'}}>Converts continuous PPFD intensity into cumulative photons delivered over 24 hours.</div></div><div style={{display:'flex',gap:'10px',marginBottom:'15px'}}><div style={{flex:1}}><label style={{...labelStyle,color:'#f59e0b'}}>PPFD (µmol/m²/s)<input type="number" value={ppfd} onChange={e=>setPpfd(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={{...labelStyle,color:'#f59e0b'}}>Light Hours/Day<input type="number" value={lightHours} onChange={e=>setLightHours(e.target.value)} style={inputStyle} /></label></div></div><div style={{background:'#000',padding:'15px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><strong style={{color:'#fff',fontSize:'1.1em'}}>Total DLI:</strong><strong style={{color:dli>=40?'#ef4444':'#00cc66',fontSize:'1.4em'}}>{dli.toFixed(1)} <span style={{fontSize:'0.6em',color:'#888'}}>mol/m²/d</span></strong></div></div>
<div style={{...cardStyle,borderTop:'4px solid #00ffff'}}><h3 style={{margin:'0 0 6px 0',color:'#00ffff'}}>CO2 Tent Injection Engine</h3><div style={{display:'flex',gap:'8px',marginBottom:'10px'}}><div style={{flex:1}}><label style={labelStyle}>L (ft)<input type="number" value={tentL} onChange={e=>setTentL(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={labelStyle}>W (ft)<input type="number" value={tentW} onChange={e=>setTentW(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={labelStyle}>H (ft)<input type="number" value={tentH} onChange={e=>setTentH(e.target.value)} style={inputStyle} /></label></div></div><div style={{marginBottom:'12px'}}><label style={labelStyle}>Target CO2 (PPM)<input type="number" value={targetCo2} onChange={e=>setTargetCo2(e.target.value)} style={inputStyle} /></label></div><div style={{background:'#000',padding:'12px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><span style={{color:'#aaa',fontSize:'0.9em'}}>Tent Volume: <strong>{tentCuFt.toFixed(1)} cu ft</strong></span><strong style={{color:'#00ffff',fontSize:'1.2em'}}>+{co2NeededCuFt.toFixed(3)} cu ft CO2</strong></div></div>
<div style={{...cardStyle,borderTop:'4px solid #3b82f6'}}><h3 style={{margin:'0 0 6px 0',color:'#3b82f6'}}>Ventilation & Exhaust CFM Sizer</h3><div style={{marginBottom:'12px',display:'flex',alignItems:'center',gap:'10px'}}><input type="checkbox" checked={hasFilter} onChange={e=>setHasFilter(e.target.checked)} style={{width:'20px',height:'20px'}} /><span style={{color:'#aaa',fontSize:'0.9em'}}>Carbon Filter / Ducting Restriction (+35% drag)</span></div><div style={{background:'#000',padding:'12px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><span style={{color:'#aaa'}}>Min Fan Rating:</span><strong style={{color:'#3b82f6',fontSize:'1.3em'}}>{Math.ceil(reqCfm)} CFM</strong></div></div>
<div style={{...cardStyle,borderTop:'4px solid #a855f7'}}><h3 style={{margin:'0 0 6px 0',color:'#a855f7'}}>Electrical Operating Cost</h3><div style={{display:'flex',gap:'10px',marginBottom:'12px'}}><div style={{flex:1}}><label style={{...labelStyle,color:'#a855f7'}}>Total Watts<input type="number" value={powerWatts} onChange={e=>setPowerWatts(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={{...labelStyle,color:'#a855f7'}}>Cost / kWh ($)<input type="number" step="0.01" value={kwhRate} onChange={e=>setKwhRate(e.target.value)} style={inputStyle} /></label></div></div><div style={{background:'#000',padding:'12px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><span style={{color:'#aaa'}}>Est. Monthly Draw:</span><strong style={{color:'#00cc66',fontSize:'1.2em'}}>${monthlyCost.toFixed(2)} / mo</strong></div></div>
</>)}
{activeTab==='Nutrients'&&(<>
<div style={{...cardStyle,borderTop:'4px solid #3b82f6'}}><h3 style={{margin:'0 0 6px 0',color:'#3b82f6'}}>Runoff Delta Tracker</h3><div style={infoBlockStyle}><div style={{color:'#00ffff',fontWeight:'bold'}}>What it does:</div><div style={{color:'#ccc'}}>Measures difference between feed minerals and drainage to detect salt lockout.</div></div><div style={{display:'flex',gap:'10px',marginBottom:'15px'}}><div style={{flex:1}}><label style={{...labelStyle,color:'#3b82f6'}}>Feed PPM<input type="number" value={feedPpm} onChange={e=>setFeedPpm(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={{...labelStyle,color:'#3b82f6'}}>Runoff PPM<input type="number" value={runoffPpm} onChange={e=>setRunoffPpm(e.target.value)} style={inputStyle} /></label></div></div><div style={{background:'#000',padding:'15px',borderRadius:'8px',border:'1px solid #222',textAlign:'center'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'10px'}}><strong style={{color:'#fff'}}>PPM Delta:</strong><strong style={{color:ppmDelta>0?'#ef4444':'#3b82f6',fontSize:'1.3em'}}>{ppmDelta>0?'+':''}{ppmDelta} PPM</strong></div><div style={{padding:'8px',background:'rgba(255,255,255,0.05)',borderRadius:'6px',color:runoffStatus.color,fontWeight:'bold'}}>{runoffStatus.text}</div></div></div>
<div style={{...cardStyle,borderTop:'4px solid #00ffff'}}><h3 style={{margin:'0 0 6px 0',color:'#00ffff'}}>EC to PPM Dual-Scale Bridge</h3><div style={{marginBottom:'15px'}}><label style={labelStyle}>Electrical Conductivity (EC / mS/cm)<input type="number" step="0.1" value={inputEc} onChange={e=>setInputEc(e.target.value)} style={{...inputStyle,borderColor:'#00ffff'}} /></label></div><div style={{display:'flex',gap:'10px'}}><div style={{flex:1,background:'#000',padding:'12px',borderRadius:'8px',border:'1px solid #222',textAlign:'center'}}><span style={{color:'#888',fontSize:'0.75em',display:'block',textTransform:'uppercase'}}>500 Scale (Hanna)</span><strong style={{color:'#00cc66',fontSize:'1.3em'}}>{ppm500.toFixed(0)} PPM</strong></div><div style={{flex:1,background:'#000',padding:'12px',borderRadius:'8px',border:'1px solid #222',textAlign:'center'}}><span style={{color:'#888',fontSize:'0.75em',display:'block',textTransform:'uppercase'}}>700 Scale (Truncheon)</span><strong style={{color:'#f59e0b',fontSize:'1.3em'}}>{ppm700.toFixed(0)} PPM</strong></div></div></div>
<div style={{...cardStyle,borderTop:'4px solid #ef4444'}}><h3 style={{margin:'0 0 6px 0',color:'#ef4444'}}>Leach & Flush Volume Sizer</h3><div style={{marginBottom:'12px'}}><label style={labelStyle}>Container / Pot Size (Gal)<input type="number" value={potSizeGal} onChange={e=>setPotSizeGal(e.target.value)} style={inputStyle} /></label></div><div style={{background:'#000',padding:'12px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><span style={{color:'#aaa'}}>Target Flush Water:</span><strong style={{color:'#ef4444',fontSize:'1.2em'}}>{flushGal} Gallons RO</strong></div></div>
</>)}
{activeTab==='Extract'&&(<>
<div style={{...cardStyle,borderTop:'4px solid #3b82f6'}}><h3 style={{margin:'0 0 6px 0',color:'#3b82f6'}}>Wet-to-Dry Estimator</h3><div style={infoBlockStyle}><div style={{color:'#00ffff',fontWeight:'bold'}}>What it does:</div><div style={{color:'#ccc'}}>Projects cured mass from wet harvest weight based on 78% moisture dissipation.</div></div><div style={{marginBottom:'15px'}}><label style={{...labelStyle,color:'#3b82f6'}}>Fresh Chopped Wet Weight (g)<input type="number" value={wetWeight} onChange={e=>setWetWeight(e.target.value)} style={{...inputStyle,borderColor:'#3b82f6'}} /></label></div><div style={{background:'#000',padding:'15px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><strong style={{color:'#fff',fontSize:'1.1em'}}>Est. Cured Yield (22%):</strong><strong style={{color:'#3b82f6',fontSize:'1.4em'}}>{estDryYield.toFixed(1)} g</strong></div></div>
<div style={{...cardStyle,borderTop:'4px solid #f59e0b'}}><h3 style={{margin:'0 0 6px 0',color:'#f59e0b'}}>Solventless Rosin Press Yield</h3><div style={{display:'flex',gap:'10px',marginBottom:'12px'}}><div style={{flex:1}}><label style={{...labelStyle,color:'#f59e0b'}}>Flower/Hash (g)<input type="number" value={rosinInput} onChange={e=>setRosinInput(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={{...labelStyle,color:'#f59e0b'}}>Rosin Output (g)<input type="number" value={rosinOutput} onChange={e=>setRosinOutput(e.target.value)} style={inputStyle} /></label></div></div><div style={{background:'#000',padding:'12px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><span style={{color:'#aaa'}}>Press Efficiency:</span><strong style={{color:rosinYieldPct>=20?'#00cc66':'#f59e0b',fontSize:'1.3em'}}>{rosinYieldPct.toFixed(1)}% Yield</strong></div></div>
<div style={{...cardStyle,borderTop:'4px solid #ef4444'}}><h3 style={{margin:'0 0 6px 0',color:'#ef4444'}}>Decarboxylation Loss Engine</h3><div style={infoBlockStyle}><div style={{color:'#00ffff',fontWeight:'bold'}}>What it does:</div><div style={{color:'#ccc'}}>Calculates active yield after thermal CO2 carboxyl group detachment.</div></div><div style={{marginBottom:'12px'}}><label style={{...labelStyle,color:'#ef4444'}}>Raw Acid Form Mass (THCA/CBDA g)<input type="number" value={rawAcidMass} onChange={e=>setRawAcidMass(e.target.value)} style={inputStyle} /></label></div><div style={{background:'#000',padding:'12px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><span style={{color:'#aaa'}}>Activated Neutral Yield:</span><strong style={{color:'#ef4444',fontSize:'1.2em'}}>{postDecarbActive.toFixed(2)} g</strong></div></div>
<div style={{...cardStyle,borderTop:'4px solid #00cc66'}}><h3 style={{margin:'0 0 6px 0',color:'#00cc66'}}>Biomass Extraction Yield</h3><div style={{display:'flex',gap:'10px',marginBottom:'15px'}}><div style={{flex:1}}><label style={{...labelStyle,color:'#00cc66'}}>Input Mass (g)<input type="number" value={inputBiomass} onChange={e=>setInputBiomass(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={{...labelStyle,color:'#00cc66'}}>Target Yield (%)<input type="number" value={targetYield} onChange={e=>setTargetYield(e.target.value)} style={inputStyle} /></label></div></div><div style={{background:'#000',padding:'15px',borderRadius:'8px',display:'flex',justifyContent:'space-between',alignItems:'center',border:'1px solid #222'}}><strong style={{color:'#fff',fontSize:'1.1em'}}>Est. Crude:</strong><strong style={{color:'#00cc66',fontSize:'1.4em'}}>{estCrude.toFixed(1)} g</strong></div></div>
<div style={{...cardStyle,borderTop:'4px solid #a855f7'}}><h3 style={{margin:'0 0 6px 0',color:'#a855f7'}}>Volumetric Concentration</h3><div style={{display:'flex',gap:'10px',marginBottom:'10px'}}><div style={{flex:1}}><label style={{...labelStyle,color:'#a855f7'}}>Crude Mass (g)<input type="number" value={crudeMass} onChange={e=>setCrudeMass(e.target.value)} style={inputStyle} /></label></div><div style={{flex:1}}><label style={{...labelStyle,color:'#a855f7'}}>Purity (%)<input type="number" value={crudePurity} onChange={e=>setCrudePurity(e.target.value)} style={inputStyle} /></label></div></div><div style={{marginBottom:'15px'}}><label style={{...labelStyle,color:'#00ffff'}}>Carrier Volume (mL)<input type="number" value={carrierVol} onChange={e=>setCarrierVol(e.target.value)} style={{...inputStyle,borderColor:'#00ffff'}} /></label></div><div style={{background:'#000',padding:'15px',borderRadius:'8px',border:'1px solid #222'}}><div style={{display:'flex',justifyContent:'space-between',color:'#aaa',marginBottom:'10px',borderBottom:'1px dashed #333',paddingBottom:'10px'}}><span>Total Active:</span> <span>{totalActive.toFixed(0)} mg</span></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong style={{color:'#fff',fontSize:'1.1em'}}>Concentration:</strong><strong style={{color:'#a855f7',fontSize:'1.4em'}}>{concentration.toFixed(1)} mg / mL</strong></div></div></div>
</>)}
{activeTab==='Guide'&&(<>
<div style={{display:'flex',gap:'6px',marginBottom:'15px',overflowX:'auto',scrollbarWidth:'none'}}>{['Lighting','Pro Tips','Compliance','Terpenes','Harvest','Deficiencies','Soil & NPK','Climate','Cloning','Training','Flowering','IPM'].map(sub=>(<button key={sub} onClick={()=>setGuideTab(sub)} style={{flex:1,padding:'8px 10px',borderRadius:'6px',fontSize:'0.82em',fontWeight:'bold',border:'none',whiteSpace:'nowrap',background:guideTab===sub?'rgba(0,204,102,0.2)':'#151515',color:guideTab===sub?'#00cc66':'#888',border:guideTab===sub?'1px solid #00cc66':'1px solid #222'}}>{sub}</button>))}</div>
{guideTab==='Lighting'&&(
<div style={{display:'flex',flexDirection:'column',gap:'12px'}}>
<div style={{...cardStyle,borderLeft:'4px solid #f59e0b'}}><h3 style={{margin:'0 0 6px 0',color:'#f59e0b'}}>Grow Light Technologies</h3><ul style={{color:'#aaa',fontSize:'0.85em',paddingLeft:'16px',lineHeight:'1.5',margin:0}}><li><strong>LED:</strong> Gold standard. Highly efficient, low heat, full-spectrum. Best for strict electrical budgets.</li><li><strong>CMH:</strong> Excellent broad spectrum and penetration, running cooler than HPS.</li><li><strong>HPS:</strong> Traditional heavy-yield flowering light (red-dominant). Draws heavy power and requires serious active cooling.</li></ul></div>
<div style={{...cardStyle,borderLeft:'4px solid #00ffff'}}><h3 style={{margin:'0 0 6px 0',color:'#00ffff'}}>Key Lighting Metrics</h3><ul style={{color:'#aaa',fontSize:'0.85em',paddingLeft:'16px',lineHeight:'1.5',margin:0}}><li><strong>Actual Wattage:</strong> True power drawn from the wall, NOT the "equivalent" marketing number.</li><li><strong>Spectrum:</strong> 5000K–6500K (blue) for veg, 2000K–3000K (red) for flowering.</li><li><strong>PPFD (µmol/m²/s):</strong> Measures usable light hitting the canopy. Target 300-500 for Veg, 800-1000 for Flower.</li></ul></div></div>)}
{guideTab==='Pro Tips'&&(
<div style={{display:'flex',flexDirection:'column',gap:'12px'}}>
<div style={{...cardStyle,borderLeft:'4px solid #00ffff'}}><h3 style={{margin:'0 0 6px 0',color:'#00ffff'}}>Leaf Surface Temp Offset</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0,lineHeight:'1.4'}}>Active transpiration cools leaves <strong>2°F to 5°F below ambient air</strong>. Measure canopy tops with IR thermometer for precision VPD.</p></div>
<div style={{...cardStyle,borderLeft:'4px solid #3b82f6'}}><h3 style={{margin:'0 0 6px 0',color:'#3b82f6'}}>Dissolved Oxygen & Temp</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0,lineHeight:'1.4'}}>Maintain nutrient water strictly at <strong>65°F to 68°F</strong>. Water above 72°F loses oxygen and breeds Pythium (root rot).</p></div>
<div style={{...cardStyle,borderLeft:'4px solid #f59e0b'}}><h3 style={{margin:'0 0 6px 0',color:'#f59e0b'}}>Canopy Saturation Thresholds</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0,lineHeight:'1.4'}}>Without CO2 enrichment, leaves hit saturation around <strong>40–45 DLI (~900–1000 PPFD)</strong>. Pushing higher bleaches colas.</p></div></div>)}
{guideTab==='Compliance'&&(
<div style={{display:'flex',flexDirection:'column',gap:'12px'}}>
<div style={{...cardStyle,borderLeft:'4px solid #ef4444'}}><h3 style={{margin:'0 0 6px 0',color:'#ef4444'}}>Legal Framework & Processing Laws</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0,lineHeight:'1.4'}}>• <strong>Hemp Threshold:</strong> Federal limits dry-weight Δ9-THC to 0.3%.<br/>• <strong>Volatile Solvents:</strong> Residential butane/propane extractions are criminalized in most jurisdictions.</p></div></div>)}
{guideTab==='Terpenes'&&(
<div style={{display:'flex',flexDirection:'column',gap:'12px'}}>
<div style={{...cardStyle,borderLeft:'4px solid #f59e0b'}}><h3 style={{margin:'0 0 4px 0',color:'#f59e0b'}}>Myrcene (332°F)</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0}}><strong>Aroma:</strong> Earthy. <strong>Effects:</strong> Sedating.</p></div>
<div style={{...cardStyle,borderLeft:'4px solid #00ffff'}}><h3 style={{margin:'0 0 4px 0',color:'#00ffff'}}>Limonene (349°F)</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0}}><strong>Aroma:</strong> Citrus. <strong>Effects:</strong> Mood elevation.</p></div></div>)}
{guideTab==='Harvest'&&(
<div style={{...cardStyle,borderLeft:'4px solid #00cc66'}}><h3 style={{margin:'0 0 8px 0',color:'#00cc66'}}>Trichome Maturity</h3><ul style={{color:'#aaa',fontSize:'0.85em',paddingLeft:'16px',lineHeight:'1.5',margin:0}}><li><strong>Milky:</strong> Peak potency.</li><li><strong>Amber:</strong> Degradation into sedative CBN.</li></ul></div>)}
{guideTab==='Deficiencies'&&(
<div style={{display:'flex',flexDirection:'column',gap:'12px'}}>
<div style={{...cardStyle,borderLeft:'4px solid #f59e0b'}}><h3 style={{margin:'0 0 8px 0',color:'#f59e0b'}}>Nitrogen (N)</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0}}>Lower leaves yellowing.</p></div>
<div style={{...cardStyle,borderLeft:'4px solid #a855f7'}}><h3 style={{margin:'0 0 8px 0',color:'#a855f7'}}>Phosphorus (P)</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0}}>Dark purple petioles, stunted growth.</p></div></div>)}
{guideTab==='Soil & NPK'&&(
<div style={{...cardStyle,borderLeft:'4px solid #00cc66'}}><h3 style={{margin:'0 0 8px 0',color:'#00cc66'}}>The Mixing Order</h3><ol style={{color:'#fff',fontSize:'0.85em',paddingLeft:'16px',lineHeight:'1.5',margin:0}}><li>Silica</li><li>Cal/Mag</li><li>Base</li><li>PK Boosters</li><li>pH Correction</li><li>Microbes</li></ol></div>)}
{guideTab==='Climate'&&(
<div style={{...cardStyle,borderLeft:'4px solid #00ffff'}}><h3 style={{margin:'0 0 8px 0',color:'#00ffff'}}>Climate Parameters</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0,lineHeight:'1.5'}}>• <strong>Veg RH:</strong> 50–65% | <strong>Bloom RH:</strong> 35–45%</p></div>)}
{guideTab==='Cloning'&&(
<div style={{...cardStyle,borderLeft:'4px solid #3b82f6'}}><h3 style={{margin:'0 0 8px 0',color:'#3b82f6'}}>Cloning</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0}}>Make razor cuts at 45° angle, dip in rooting hormone.</p></div>)}
{guideTab==='Training'&&(
<div style={{...cardStyle,borderLeft:'4px solid #ef4444'}}><h3 style={{margin:'0 0 8px 0',color:'#ef4444'}}>Canopy Management</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0}}>Top main stem above the 5th node. Use trellis nets.</p></div>)}
{guideTab==='Flowering'&&(
<div style={{...cardStyle,borderLeft:'4px solid #a855f7'}}><h3 style={{margin:'0 0 8px 0',color:'#a855f7'}}>The 12/12 Flip</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0}}>Transition timers to 12 ON / 12 OFF. Zero light leaks.</p></div>)}
{guideTab==='IPM'&&(
<div style={{...cardStyle,borderLeft:'4px solid #ef4444'}}><h3 style={{margin:'0 0 8px 0',color:'#ef4444'}}>Integrated Pest Management</h3><p style={{color:'#aaa',fontSize:'0.85em',margin:0}}>Rotate cold-pressed Neem weekly during veg. Never spray flowers.</p></div>)}
</>)}
</div></div>);
}
